name: Update schemas

on:
  schedule:
    # Daily
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-odb-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.LUCUMA_STEWARD_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_GH_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: pnpm install
        run: pnpm install --frozen-lockfile --filter lucuma-schemas --prefer-offline

      - name: Install dependencies and fetch latest ODB schema
        run: pnpm schemas fetch-schema dev
        env:
          ODB_API_KEY: ${{ secrets.LUCUMA_DEV_API_KEY }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update ODB Schema
          commit-message: Update ODB Schema
          committer: lucuma-steward[bot] <106720676+lucuma-steward[bot]@users.noreply.github.com>
          author: lucuma-steward[bot] <106720676+lucuma-steward[bot]@users.noreply.github.com>
          branch: steward/update-odb-schema
          delete-branch: true
          token: ${{ steps.generate-token.outputs.token }}
      - name: Check Pull Request
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
